name: Todd Vaccaro
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0.7865504855290055
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
